WITH FKEYs (TABLE_NAME, FK_TABLE_NAME, FK_NAME, Level)
AS
(
select		TC2.TABLE_NAME,TC1.TABLE_NAME,TC1.CONSTRAINT_NAME,0
FROM		INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
JOIN		INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC1
	ON	RC.CONSTRAINT_NAME = TC1.CONSTRAINT_NAME

JOIN		INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC2
	ON	RC.UNIQUE_CONSTRAINT_NAME = TC2.CONSTRAINT_NAME	
--WHERE		TC2.TABLE_NAME NOT IN (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE constraint_Type ='Foreign Key')
WHERE		TC2.TABLE_NAME IN	(
					SELECT distinct object_Name(so.id) AS TableName
					FROM sysobjects so
					join syscolumns sc
					on so.id = sc.id
					where	so.type = 'u'
					and	sc.name like '%assetid%'
					)

UNION ALL
select		TC2.TABLE_NAME,TC1.TABLE_NAME,TC1.CONSTRAINT_NAME,Level+1
FROM		INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
JOIN		INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC1
	ON	RC.CONSTRAINT_NAME = TC1.CONSTRAINT_NAME

JOIN		INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC2
	ON	RC.UNIQUE_CONSTRAINT_NAME = TC2.CONSTRAINT_NAME	
JOIN		FKEYs FK
	ON	TC2.TABLE_NAME = FK.FK_TABLE_NAME
)
-- Statement that executes the common table expression
SELECT TABLE_NAME, FK_TABLE_NAME, FK_NAME
FROM FKEYs