SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
DECLARE @ROOT_TABLE_NAME VarChar(255) 
DECLARE	@TABLE_TREE	TABLE
	(
	TREE_LEVEL	INT NOT NULL,
	PARENT_NAME	sysname NULL,
	TABLE_NAME	sysname NOT NULL,
	PATH		VarChar(900) NOT NULL PRIMARY KEY CLUSTERED
	)

SET       @ROOT_TABLE_NAME = 'SystemUser'
	
	IF ((OBJECT_ID(@ROOT_TABLE_NAME) IS NULL) OR (@ROOT_TABLE_NAME IS NULL))
		INSERT INTO	@TABLE_TREE
		SELECT		DISTINCT
				0,
				NULL,
				PARENT_TABLE_NAME,
				'\' + PARENT_TABLE_NAME
		FROM		(select		DISTINCT
						T1.TABLE_NAME AS PARENT_TABLE_NAME,
						T4.TABLE_NAME AS CHILD_TABLE_NAME,
						T21.COLUMN_NAME AS PARENT_KEY_COLUMN_1,
						T22.COLUMN_NAME AS PARENT_KEY_COLUMN_2,
						T23.COLUMN_NAME AS PARENT_KEY_COLUMN_3,
						T24.COLUMN_NAME AS PARENT_KEY_COLUMN_4,
						T25.COLUMN_NAME AS PARENT_KEY_COLUMN_5,
						T26.COLUMN_NAME AS PARENT_KEY_COLUMN_6,
						T27.COLUMN_NAME AS PARENT_KEY_COLUMN_7,
						T28.COLUMN_NAME AS PARENT_KEY_COLUMN_8,
						T29.COLUMN_NAME AS PARENT_KEY_COLUMN_9,
						T41.COLUMN_NAME AS CHILD_KEY_COLUMN_1,
						T42.COLUMN_NAME AS CHILD_KEY_COLUMN_2,
						T43.COLUMN_NAME AS CHILD_KEY_COLUMN_3,
						T44.COLUMN_NAME AS CHILD_KEY_COLUMN_4,
						T45.COLUMN_NAME AS CHILD_KEY_COLUMN_5,
						T46.COLUMN_NAME AS CHILD_KEY_COLUMN_6,
						T47.COLUMN_NAME AS CHILD_KEY_COLUMN_7,
						T48.COLUMN_NAME AS CHILD_KEY_COLUMN_8,
						T49.COLUMN_NAME AS CHILD_KEY_COLUMN_9
				FROM		INFORMATION_SCHEMA.TABLES			T1
				Left Join	INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE	T2
					ON	T2.TABLE_NAME = T1.TABLE_NAME
				Left Join	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS	T3
					ON	T3.UNIQUE_CONSTRAINT_NAME = T2.CONSTRAINT_NAME
				Left Join	INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE	T4
					ON	T4.CONSTRAINT_NAME = T3.CONSTRAINT_NAME
				-- Now The Parent Key Columns
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T21
					ON	T21.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T21.ORDINAL_POSITION = 1
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T22
					ON	T22.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T22.ORDINAL_POSITION = 2
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T23
					ON	T23.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T23.ORDINAL_POSITION = 3
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T24
					ON	T24.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T24.ORDINAL_POSITION = 4
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T25
					ON	T25.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T25.ORDINAL_POSITION = 5
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T26
					ON	T26.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T26.ORDINAL_POSITION = 6
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T27
					ON	T27.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T27.ORDINAL_POSITION = 7
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T28
					ON	T28.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T28.ORDINAL_POSITION = 8
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T29
					ON	T29.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T29.ORDINAL_POSITION = 9
				-- Now The Child Key Columns
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T41
					ON	T41.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T41.ORDINAL_POSITION = 1
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T42
					ON	T42.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T42.ORDINAL_POSITION = 2
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T43
					ON	T43.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T43.ORDINAL_POSITION = 3
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T44
					ON	T44.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T44.ORDINAL_POSITION = 4
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T45
					ON	T45.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T45.ORDINAL_POSITION = 5
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T46
					ON	T46.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T46.ORDINAL_POSITION = 6
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T47
					ON	T47.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T47.ORDINAL_POSITION = 7
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T48
					ON	T48.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T48.ORDINAL_POSITION = 8
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T49
					ON	T49.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T49.ORDINAL_POSITION = 9
				WHERE		T1.TABLE_TYPE = 'BASE TABLE'
					AND	OBJECTPROPERTY(OBJECT_ID(T1.TABLE_NAME),'IsMSShipped') = 0
					AND	OBJECTPROPERTY(OBJECT_ID(T1.TABLE_NAME),'IsUserTable') = 1
					AND	OBJECTPROPERTY(OBJECT_ID(COALESCE(T4.TABLE_NAME,T1.TABLE_NAME)),'IsMSShipped') = 0
					AND	OBJECTPROPERTY(OBJECT_ID(COALESCE(T4.TABLE_NAME,T1.TABLE_NAME)),'IsUserTable') = 1
					AND	T1.TABLE_NAME <> COALESCE(T4.TABLE_NAME,'')
				)TABLE_KEY_RELATIONS
		WHERE		PARENT_TABLE_NAME NOT IN (SELECT DISTINCT CHILD_TABLE_NAME FROM (select		DISTINCT
		T1.TABLE_NAME AS PARENT_TABLE_NAME,
		T4.TABLE_NAME AS CHILD_TABLE_NAME,
		T21.COLUMN_NAME AS PARENT_KEY_COLUMN_1,
		T22.COLUMN_NAME AS PARENT_KEY_COLUMN_2,
		T23.COLUMN_NAME AS PARENT_KEY_COLUMN_3,
		T24.COLUMN_NAME AS PARENT_KEY_COLUMN_4,
		T25.COLUMN_NAME AS PARENT_KEY_COLUMN_5,
		T26.COLUMN_NAME AS PARENT_KEY_COLUMN_6,
		T27.COLUMN_NAME AS PARENT_KEY_COLUMN_7,
		T28.COLUMN_NAME AS PARENT_KEY_COLUMN_8,
		T29.COLUMN_NAME AS PARENT_KEY_COLUMN_9,
		T41.COLUMN_NAME AS CHILD_KEY_COLUMN_1,
		T42.COLUMN_NAME AS CHILD_KEY_COLUMN_2,
		T43.COLUMN_NAME AS CHILD_KEY_COLUMN_3,
		T44.COLUMN_NAME AS CHILD_KEY_COLUMN_4,
		T45.COLUMN_NAME AS CHILD_KEY_COLUMN_5,
		T46.COLUMN_NAME AS CHILD_KEY_COLUMN_6,
		T47.COLUMN_NAME AS CHILD_KEY_COLUMN_7,
		T48.COLUMN_NAME AS CHILD_KEY_COLUMN_8,
		T49.COLUMN_NAME AS CHILD_KEY_COLUMN_9
FROM		INFORMATION_SCHEMA.TABLES			T1
Left Join	INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE	T2
	ON	T2.TABLE_NAME = T1.TABLE_NAME
Left Join	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS	T3
	ON	T3.UNIQUE_CONSTRAINT_NAME = T2.CONSTRAINT_NAME
Left Join	INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE	T4
	ON	T4.CONSTRAINT_NAME = T3.CONSTRAINT_NAME
-- Now The Parent Key Columns
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T21
	ON	T21.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T21.ORDINAL_POSITION = 1
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T22
	ON	T22.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T22.ORDINAL_POSITION = 2
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T23
	ON	T23.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T23.ORDINAL_POSITION = 3
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T24
	ON	T24.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T24.ORDINAL_POSITION = 4
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T25
	ON	T25.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T25.ORDINAL_POSITION = 5
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T26
	ON	T26.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T26.ORDINAL_POSITION = 6
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T27
	ON	T27.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T27.ORDINAL_POSITION = 7
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T28
	ON	T28.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T28.ORDINAL_POSITION = 8
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T29
	ON	T29.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
	AND	T29.ORDINAL_POSITION = 9
-- Now The Child Key Columns
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T41
	ON	T41.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T41.ORDINAL_POSITION = 1
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T42
	ON	T42.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T42.ORDINAL_POSITION = 2
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T43
	ON	T43.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T43.ORDINAL_POSITION = 3
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T44
	ON	T44.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T44.ORDINAL_POSITION = 4
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T45
	ON	T45.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T45.ORDINAL_POSITION = 5
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T46
	ON	T46.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T46.ORDINAL_POSITION = 6
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T47
	ON	T47.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T47.ORDINAL_POSITION = 7
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T48
	ON	T48.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T48.ORDINAL_POSITION = 8
Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T49
	ON	T49.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
	AND	T49.ORDINAL_POSITION = 9
WHERE		T1.TABLE_TYPE = 'BASE TABLE'
	AND	OBJECTPROPERTY(OBJECT_ID(T1.TABLE_NAME),'IsMSShipped') = 0
	AND	OBJECTPROPERTY(OBJECT_ID(T1.TABLE_NAME),'IsUserTable') = 1
	AND	OBJECTPROPERTY(OBJECT_ID(COALESCE(T4.TABLE_NAME,T1.TABLE_NAME)),'IsMSShipped') = 0
	AND	OBJECTPROPERTY(OBJECT_ID(COALESCE(T4.TABLE_NAME,T1.TABLE_NAME)),'IsUserTable') = 1
	AND	T1.TABLE_NAME <> COALESCE(T4.TABLE_NAME,'')) Data WHERE CHILD_TABLE_NAME IS NOT NULL AND  CHILD_TABLE_NAME != PARENT_TABLE_NAME)
	ELSE
		INSERT INTO	@TABLE_TREE
		SELECT		0,
				NULL,
				@ROOT_TABLE_NAME,
				'\' + @ROOT_TABLE_NAME
	WHILE	1<2
	BEGIN
		INSERT INTO	@TABLE_TREE
		SELECT		RELATED_TABLES.*
		FROM		(
				SELECT		DISTINCT
						TT.TREE_LEVEL + 1				AS TREE_LEVEL,
						TT.TABLE_NAME					AS PARENT_NAME,
						TKR.CHILD_TABLE_NAME				AS TABLE_NAME,
						TT.PATH + '\' + TKR.CHILD_TABLE_NAME		AS PATH 
				FROM		@TABLE_TREE					TT
				INNER JOIN	(select		DISTINCT
						T1.TABLE_NAME AS PARENT_TABLE_NAME,
						T4.TABLE_NAME AS CHILD_TABLE_NAME,
						T21.COLUMN_NAME AS PARENT_KEY_COLUMN_1,
						T22.COLUMN_NAME AS PARENT_KEY_COLUMN_2,
						T23.COLUMN_NAME AS PARENT_KEY_COLUMN_3,
						T24.COLUMN_NAME AS PARENT_KEY_COLUMN_4,
						T25.COLUMN_NAME AS PARENT_KEY_COLUMN_5,
						T26.COLUMN_NAME AS PARENT_KEY_COLUMN_6,
						T27.COLUMN_NAME AS PARENT_KEY_COLUMN_7,
						T28.COLUMN_NAME AS PARENT_KEY_COLUMN_8,
						T29.COLUMN_NAME AS PARENT_KEY_COLUMN_9,
						T41.COLUMN_NAME AS CHILD_KEY_COLUMN_1,
						T42.COLUMN_NAME AS CHILD_KEY_COLUMN_2,
						T43.COLUMN_NAME AS CHILD_KEY_COLUMN_3,
						T44.COLUMN_NAME AS CHILD_KEY_COLUMN_4,
						T45.COLUMN_NAME AS CHILD_KEY_COLUMN_5,
						T46.COLUMN_NAME AS CHILD_KEY_COLUMN_6,
						T47.COLUMN_NAME AS CHILD_KEY_COLUMN_7,
						T48.COLUMN_NAME AS CHILD_KEY_COLUMN_8,
						T49.COLUMN_NAME AS CHILD_KEY_COLUMN_9
				FROM		INFORMATION_SCHEMA.TABLES			T1
				Left Join	INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE	T2
					ON	T2.TABLE_NAME = T1.TABLE_NAME
				Left Join	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS	T3
					ON	T3.UNIQUE_CONSTRAINT_NAME = T2.CONSTRAINT_NAME
				Left Join	INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE	T4
					ON	T4.CONSTRAINT_NAME = T3.CONSTRAINT_NAME
				-- Now The Parent Key Columns
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T21
					ON	T21.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T21.ORDINAL_POSITION = 1
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T22
					ON	T22.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T22.ORDINAL_POSITION = 2
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T23
					ON	T23.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T23.ORDINAL_POSITION = 3
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T24
					ON	T24.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T24.ORDINAL_POSITION = 4
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T25
					ON	T25.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T25.ORDINAL_POSITION = 5
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T26
					ON	T26.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T26.ORDINAL_POSITION = 6
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T27
					ON	T27.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T27.ORDINAL_POSITION = 7
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T28
					ON	T28.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T28.ORDINAL_POSITION = 8
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T29
					ON	T29.CONSTRAINT_NAME = T2.CONSTRAINT_NAME
					AND	T29.ORDINAL_POSITION = 9
				-- Now The Child Key Columns
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T41
					ON	T41.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T41.ORDINAL_POSITION = 1
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T42
					ON	T42.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T42.ORDINAL_POSITION = 2
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T43
					ON	T43.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T43.ORDINAL_POSITION = 3
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T44
					ON	T44.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T44.ORDINAL_POSITION = 4
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T45
					ON	T45.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T45.ORDINAL_POSITION = 5
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T46
					ON	T46.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T46.ORDINAL_POSITION = 6
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T47
					ON	T47.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T47.ORDINAL_POSITION = 7
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T48
					ON	T48.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T48.ORDINAL_POSITION = 8
				Left Join	INFORMATION_SCHEMA.KEY_COLUMN_USAGE		T49
					ON	T49.CONSTRAINT_NAME = T4.CONSTRAINT_NAME
					AND	T49.ORDINAL_POSITION = 9
				WHERE		T1.TABLE_TYPE = 'BASE TABLE'
					AND	OBJECTPROPERTY(OBJECT_ID(T1.TABLE_NAME),'IsMSShipped') = 0
					AND	OBJECTPROPERTY(OBJECT_ID(T1.TABLE_NAME),'IsUserTable') = 1
					AND	OBJECTPROPERTY(OBJECT_ID(COALESCE(T4.TABLE_NAME,T1.TABLE_NAME)),'IsMSShipped') = 0
					AND	OBJECTPROPERTY(OBJECT_ID(COALESCE(T4.TABLE_NAME,T1.TABLE_NAME)),'IsUserTable') = 1
					AND	T1.TABLE_NAME <> COALESCE(T4.TABLE_NAME,'')
				)TKR
					ON	TKR.PARENT_TABLE_NAME	= TT.TABLE_NAME
					AND	TKR.CHILD_TABLE_NAME	!= TT.TABLE_NAME
				)								RELATED_TABLES
		LEFT JOIN	@TABLE_TREE							TT
			ON	TT.PATH			= RELATED_TABLES.PATH
		WHERE		TT.PATH			IS NULL
			AND	RELATED_TABLES.PATH	IS NOT NULL
		IF @@ROWCOUNT = 0 BREAK


	END

SELECT * FROM @TABLE_TREE
