SELECT		dbaadmin.dbo.dbaudf_CPUInfo('Cores')		AS [NumberOfCPUCores]
		,dbaadmin.dbo.dbaudf_CPUInfo('Processors')	AS [NumberOfCPUProcessors]
		,dbaadmin.dbo.dbaudf_CPUInfo('Sockets')		AS [NumberOfCPUSockets]
		,[SQLver]
		,[OSver]
		,[CLR_state]
		,[PowerShell]
		,[SQLEnv]
		,[DomainName]
		,[SystemModel]
FROM		dbaadmin.[dbo].[DBA_ServerInfo]