
DECLARE	@OldServerName	SYSNAME = @@ServerName
	,@NewServerName	SYSNAME = CAST(SERVERPROPERTY('ComputerNamePhysicalNetBIOS') AS SYSNAME) +ISNULL(NULLIF('\'+@@SERVICENAME,'\MSSQLSERVER'),'')


IF @OldServerName != @NewServerName
BEGIN
	RAISERROR ('SERVER %s HAS BEEN RENAMED TO %s BUT SYSSERVERS HAS NOT BEEN UPDATED',-1,-1,@OldServerName,@NewServerName) WITH NOWAIT
	RAISERROR ('SYSSERVERS UPDATED RUNNING NOW.',-1,-1) WITH NOWAIT

	RAISERROR ('   DROPPING SERVER %s...',-1,-1,@OldServerName) WITH NOWAIT
		exec sp_dropserver @OldServerName

	RAISERROR ('   ADDING SERVER %s...',-1,-1,@NewServerName) WITH NOWAIT
		exec sp_addserver @NewServerName, local

	RAISERROR ('SYSSERVERS UPDATED IS COMPLEATE. SQL MUST BE RESTARTED TO TAKE EFFECT',-1,-1) WITH NOWAIT
END
ELSE 
	RAISERROR ('NO SYSSERVERS UPDATED IS NEEDED.',-1,-1) WITH NOWAIT