GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Allsps TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_CPU_Utilization TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Execution_TopSPs TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Execution_TopFNs TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Dbspace_Usage_Sumall TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_IO_Top4 TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_RecentBackups TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Blocked_Sessions TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_IndexFrag TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TablesWithPKs TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TablesWithoutPKs TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TablesWithoutClusteredIndexes TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TablesWithoutAnyIndexes TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_RecordCounts TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TopElapsed TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TopCPU TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TopIO TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Gather_Wait_Stats TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Wait_Stat_Percentage TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TasksWaitingToRun TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TopIO_DB TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_DiskSpace TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_MissingIndexes TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Wait_Stats TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_TopIOSPs TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Top5IO_DB TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Blocked_Processes TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_CPU_Top4 TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Unused_Indexes TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Dbspace_Usage TO programmer
GRANT EXECUTE on DBAADMIN.DBA_Dashboard.Get_Dbspace_Usage_All TO programmer
go 
USE master
go
GRANT VIEW SERVER STATE TO programmer