use master;
go
DECLARE		@Port			VarChar(10)
DECLARE		@TSQL			VarChar(max)
DECLARE		@Password		VarChar(50)
DECLARE		@EndpointName	sysname
DECLARE		@NoBackup		BIT
DECLARE		@DropOnly		BIT
SET			@DropOnly		= 1
SET			@NoBackup		= 0
SET			@Port			= '4022'
SET			@Password		= 'L84Lunch'
SET			@EndpointName	= 'broker'


IF Exists (Select * From sys.Endpoints where name = @EndpointName)
BEGIN
	SET @TSQL = REPLACE(
	'DROP ENDPOINT [[ENDPOINTNAME]];'
	,'[[ENDPOINTNAME]]',@EndpointName)
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''
END

IF Exists (Select * From sys.certificates where name = ''+REPLACE(@@SERVERNAME,'\','$'))
BEGIN
	SET @TSQL = REPLACE(
	'DROP CERTIFICATE [[[SERVERNAME]]];'
	,'[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$'))
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''
END

IF NOT EXISTS(Select * From sys.certificates WHERE pvt_key_encryption_type = 'MK')
BEGIN
	IF Exists (select * From sys.symmetric_keys WHERE name = '##MS_DatabaseMasterKey##')
	BEGIN
		SET @TSQL = 'DROP MASTER KEY;'
		PRINT (@TSQL)
		EXEC (@TSQL)
		PRINT ''
	END
END

IF NOT EXISTS(select * From sys.symmetric_keys WHERE name = '##MS_DatabaseMasterKey##') AND @DropOnly = 0
BEGIN
	SET @TSQL = REPLACE(
	'CREATE MASTER KEY ENCRYPTION BY PASSWORD = ''[[Password]]'';'
	,'[[Password]]',@Password)
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''
END


IF dbaadmin.dbo.dbaudf_GetFileProperty(REPLACE(REPLACE('\\[[MACHINENAME]]\[[MACHINENAME]]_dbasql\[[SERVERNAME]].cer','[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$')),'[[MACHINENAME]]',CAST(SERVERPROPERTY('machinename') AS SYSNAME)),'File','Path') IS NOT NULL
AND dbaadmin.dbo.dbaudf_GetFileProperty(REPLACE(REPLACE('\\[[MACHINENAME]]\[[MACHINENAME]]_dbasql\[[SERVERNAME]].pvk','[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$')),'[[MACHINENAME]]',CAST(SERVERPROPERTY('machinename') AS SYSNAME)),'File','Path') IS NOT NULL
AND @DropOnly = 0
BEGIN
	SET @TSQL = REPLACE(REPLACE(
	'CREATE CERTIFICATE [[[SERVERNAME]]]
	  FROM FILE = ''\\[[MACHINENAME]]\[[MACHINENAME]]_DBASQL\[[SERVERNAME]].CER''
	  WITH PRIVATE KEY (FILE = ''\\[[MACHINENAME]]\[[MACHINENAME]]_DBASQL\[[SERVERNAME]].PVK'',
	  DECRYPTION BY PASSWORD = '''+@PASSWORD+''');'
	,'[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$'))
	,'[[MACHINENAME]]',CAST(SERVERPROPERTY('MACHINENAME') AS SYSNAME))
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''
	SET @NoBackup = 1
END
ELSE  IF @DropOnly = 0
BEGIN
	IF dbaadmin.dbo.dbaudf_GetFileProperty(REPLACE(REPLACE('\\[[MACHINENAME]]\[[MACHINENAME]]_dbasql\[[SERVERNAME]].cer','[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$')),'[[MACHINENAME]]',CAST(SERVERPROPERTY('machinename') AS SYSNAME)),'File','Path') IS NOT NULL
	BEGIN
		SET	@TSQL = REPLACE(REPLACE('EXEC XP_CMDSHELL ''DEL \\[[MACHINENAME]]\[[MACHINENAME]]_dbasql\[[SERVERNAME]].cer''','[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$')),'[[MACHINENAME]]',CAST(SERVERPROPERTY('machinename') AS SYSNAME))	
		PRINT (@TSQL)
		EXEC (@TSQL)
	END

	IF dbaadmin.dbo.dbaudf_GetFileProperty(REPLACE(REPLACE('\\[[MACHINENAME]]\[[MACHINENAME]]_dbasql\[[SERVERNAME]].pvk','[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$')),'[[MACHINENAME]]',CAST(SERVERPROPERTY('machinename') AS SYSNAME)),'File','Path') IS NOT NULL
	BEGIN
		SET	@TSQL = REPLACE(REPLACE('EXEC XP_CMDSHELL ''DEL \\[[MACHINENAME]]\[[MACHINENAME]]_dbasql\[[SERVERNAME]].pvk''','[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$')),'[[MACHINENAME]]',CAST(SERVERPROPERTY('machinename') AS SYSNAME))	
		PRINT (@TSQL)
		EXEC (@TSQL)
	END

	SET			@TSQL		= REPLACE(
	'CREATE CERTIFICATE [[[SERVERNAME]]]
	  WITH SUBJECT = ''[[SERVERNAME]]''
	  , START_DATE = ''20110101''
	  , EXPIRY_DATE = ''20151231'';'
	,'[[SERVERNAME]]',''+REPLACE(@@SERVERNAME,'\','$'))
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''
END

IF @DropOnly = 0
BEGIN
	SET			@TSQL		= REPLACE(REPLACE(REPLACE(
	'CREATE ENDPOINT [[[ENDPOINTNAME]]] 
	STATE = STARTED
	AS TCP (LISTENER_PORT = [[PORT]])
	FOR SERVICE_BROKER (AUTHENTICATION = CERTIFICATE [[[SERVERNAME]]]);'
	,'[[SERVERNAME]]',''+REPLACE(@@SERVERNAME,'\','$'))
	,'[[ENDPOINTNAME]]',@ENDPOINTNAME)
	,'[[PORT]]',@Port)
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''
END

IF @NoBackup = 0 AND @DropOnly = 0
BEGIN
	SET			@TSQL		= REPLACE(REPLACE(REPLACE(
	'BACKUP CERTIFICATE [[[SERVERNAME]]]
	TO FILE = ''\\[[MACHINENAME]]\[[MACHINENAME]]_DBASQL\[[SERVERNAME]].CER''
	WITH PRIVATE KEY (FILE = ''\\[[MACHINENAME]]\[[MACHINENAME]]_DBASQL\[[SERVERNAME]].PVK''
		,ENCRYPTION BY PASSWORD = ''[[PASSWORD]]'');'
	,'[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$'))
	,'[[MACHINENAME]]',CAST(SERVERPROPERTY('MACHINENAME') AS SYSNAME))
	,'[[PASSWORD]]',@PASSWORD)
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''
END

SET			@TSQL		= REPLACE(
'IF EXISTS (SELECT * FROM sys.sysusers WHERE name = ''[[SERVERNAME]]_SBUSER'')
	DROP USER [[SERVERNAME]]_SBUser;'
,'[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$'))
PRINT (@TSQL)
EXEC (@TSQL)
PRINT ''

IF @DropOnly = 0
BEGIN
	SET			@TSQL		= REPLACE(
	'CREATE USER [[SERVERNAME]]_SBUser WITHOUT LOGIN;'
	,'[[SERVERNAME]]',REPLACE(@@SERVERNAME,'\','$'))
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''

	SET			@TSQL		= REPLACE(REPLACE(
	'GRANT CONNECT ON ENDPOINT::[[EndpointName]] TO [[[MACHINENAME]]_SBUser];'
	,'[[MACHINENAME]]',REPLACE(@@SERVERNAME,'\','$'))
	,'[[EndpointName]]',@EndpointName)
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''
END


IF @@SERVERNAME != 'SEAPSQLDBA01' -- ONLY AT CLIENT
BEGIN
	SET			@TSQL		= REPLACE(
	'IF EXISTS (SELECT * FROM sys.sysusers WHERE name = ''[[SERVERNAME]]_SBUSER'')
		DROP USER [[SERVERNAME]]_SBUser;'
	,'[[SERVERNAME]]','SEAPSQLDBA01')
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''

	IF @DropOnly = 0
	BEGIN
		SET			@TSQL		= REPLACE(
		'CREATE USER [[SERVERNAME]]_SBUser WITHOUT LOGIN;'
		,'[[SERVERNAME]]','SEAPSQLDBA01')
		PRINT (@TSQL)
		EXEC (@TSQL)
		PRINT ''
	END		

	SET @TSQL = REPLACE(REPLACE(REPLACE(
	'IF EXISTS (SELECT * FROM sys.certificates WHERE name = ''[[SERVERNAME]]'') 
		DROP CERTIFICATE [[[SERVERNAME]]];'
	,'[[SERVERNAME]]','SEAPSQLDBA01')
	,'[[MACHINENAME]]','SEAPSQLDBA01')
	,'[[PASSWORD]]',@Password)
	PRINT (@TSQL)
	EXEC (@TSQL)
	PRINT ''

	IF @DropOnly = 0
	BEGIN
		SET @TSQL = REPLACE(REPLACE(REPLACE(
		'CREATE CERTIFICATE [[[SERVERNAME]]]
		  FROM FILE = ''\\[[MACHINENAME]]\[[MACHINENAME]]_DBASQL\[[SERVERNAME]].CER''
		  WITH PRIVATE KEY (FILE = ''\\[[MACHINENAME]]\[[MACHINENAME]]_DBASQL\[[SERVERNAME]].PVK'',
		  DECRYPTION BY PASSWORD = ''[[PASSWORD]]'');'
		,'[[SERVERNAME]]','SEAPSQLDBA01')
		,'[[MACHINENAME]]','SEAPSQLDBA01')
		,'[[PASSWORD]]',@Password)
		PRINT (@TSQL)
		EXEC (@TSQL)
		PRINT ''

		SET			@TSQL		= REPLACE(REPLACE(
		'GRANT CONNECT ON ENDPOINT::[[EndpointName]] TO [[[MACHINENAME]]_SBUser];'
		,'[[MACHINENAME]]','SEAPSQLDBA01')
		,'[[EndpointName]]',@EndpointName)
		PRINT (@TSQL)
		EXEC (@TSQL)
		PRINT ''
	END
END	

GO